language: node_js
node_js:
- '7'
install:
- npm install
script:
- npm run example
deploy:
  provider: npm
  email: shanda.lin+npm@upai.com
  api_key:
    secure: eS5aohWFI96FtuZ3odYTZ6stnax8n3waWHc+3LSA+pGmfPEQwg5+VDKRikTHF0L0BeB+hmjT1jrpw5uIEHPdi5FBhfF8ynkVyHpYNU3TfV3ex43eCjI8dx8UyNwh3qtNGLaluubtHrCt+6WkTxhG1VaQcdU/tefQhq1OhWhzfFSbDKLHPhzNi1sz+9YJgcy28weepZ1dOVuINwH0r808zv1ObV8pBqIvjl+2+atYVpjbHUHnMZn9ujXZ+osDAdErkW3bR4+XTOkRPAOQNVahV73znL2i2HoNvFbcyqZf9C4rgfSXuEs8qbiL/YFymdMw4HVfDdWWtgDlZOpJhEQGKjjW+Mxp2ZvxVuHX3WHVM0wVspFdH+upnrjUZykZduSVE6GDQKkDXWc4YQvDvbRZlEkoSXkiWjjUN00Cue46Otgc3wT1vUsVFI339hC6Yn1OkUwKeIX3k7TArCHip6PAJ7FI4r6VhqfvwW2sq6e4cNXQiYmzKKaTBF1p4i2uDLBZppLIop0YzoVL6uDh3myzMB1KxSQlRZ14/GYF1JD9+PDuywxrSHVwiKo33czDtsMUkAxJ6yFKb/Dsj0k4TjPdO8beRcAgYXyx+Z9a709GKYf7ehB7tR/pYLpr7jOyqoZzfSAGRDkrRcExlZLlqVKq16G7mCgZ860yxrhDEPI5Du4=
  on:
    tags: true
    repo: upyun-dev/qengine
env:
  global:
    secure: YoLwTjJTaSRUMZwICl2akudUeBgdLeH8Ju/fV6b3CuW4nAYA+wIdSACaBzTJNg8d3fZTOwNnL6qyhg7wMXSeiKRtmEqpJPL9SeFnpmUkqdzH1jCD8FBlSMSBpQtGHv5+GzzOKBaoMzi0IX8YJx/eCUSmIz9pHpieOqWaOAiizzAsPW4wgvqz72+tUmhPrZfwm1+9+oGHgoS1Nr2/aTgCurpq5/jGPdDPQEY+0gIdw+Z/0TpNmKrqNHO2b/RwnSH7QH26zQg2BBSna1IQXEbbcOVez143bmLgfTH3aRA+sA9iw2OX+Bm+a6eFXnOPNSwa3VwOShpL/QfrN0gvPnLUeEDhMQ/QVQ/Fkrsa6Q3XZEDNkDSDe6YbALEyeHurrS5aeLwYZSg+4byN9gArIteHqf8IVoXgxjucyt4IZJ8PmziiTclerOvviEwmSAjNjCTA8Od2duZwzIcTQCy3Nc3pNjNDch2rtlu+8U3WmPecxyAGBaIZYdqHKhSG/HlqYfQyxc1KYyBD7mnhzf6Mtp2YYB+OS0dMmWYbmYo05H03JUi4Ng+hABlxk/wefsRPxms9eP/h2NqAld+ECkF7WaxeGhUmyMNbQob/OQGn2DYrAoY6roJjdImjyE+hQ3HeM0I6FtG1dAvihV5grQQmdk4ENXYyoDkdIEUxc/5CBUc7BFA=
